name: inkwave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.4.4
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  flare_flutter: ^3.0.2
  rive: 0.13.20
  fl_chart: ^0.63.0
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1
  connectivity_plus: ^4.0.1
  csv: ^5.0.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  intl: ^0.18.1
  permission_handler: ^11.0.0
  excel: ^2.1.0
  open_file: ^3.3.2

  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.3
  google_sign_in: ^6.2.2
  firebase_messaging: ^14.7.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/app_images/inkwave.png
    - assets/app_images/book.png
    - assets/app_images/image.png
    - assets/rivs/teddy.riv
    - assets/onboarding/
    - assets/onboarding/welcome.png
    - assets/onboarding/translate.png
    - assets/onboarding/library.png
    - assets/profile_placeholder.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_images/book.png"
  adaptive_icon_foreground: "assets/app_images/book.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true

