name: inkwave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Network Requests
  http: ^1.2.1

  # External Link Handling
  url_launcher: ^6.3.0

  # WebView Support
  webview_flutter: ^4.4.4

  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/app_images/inkwave.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_images/inkwave.png"
  adaptive_icon_foreground: "assets/app_images/inkwave.png"
  adaptive_icon_background: "#121212"
