// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1iKcqKZWxJcexSdTucSAbPMDEb7pFYw',
    appId: '1:148134255966:web:2b4e57d67eb8aac68c83cf',
    messagingSenderId: '148134255966',
    projectId: 'inkwave-01',
    authDomain: 'inkwave-01.firebaseapp.com',
    storageBucket: 'inkwave-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjfwxsOpp8_gGkCkGAEQmD2eWTZv-MYY',
    appId: '1:148134255966:android:13d3cebb871faead8c83cf',
    messagingSenderId: '148134255966',
    projectId: 'inkwave-01',
    storageBucket: 'inkwave-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfb5oKSXa6UXnOndHlSXbHyADl8r_YUY',
    appId: '1:148134255966:ios:80cb5c87bcdbc10c8c83cf',
    messagingSenderId: '148134255966',
    projectId: 'inkwave-01',
    storageBucket: 'inkwave-01.firebasestorage.app',
    androidClientId: '148134255966-tp1pre8en9le6eqhmbgsb95ragmi6krv.apps.googleusercontent.com',
    iosClientId: '148134255966-tjmiktovlvuq300ehu8p0mrf7q1ok1l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.inkwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfb5oKSXa6UXnOndHlSXbHyADl8r_YUY',
    appId: '1:148134255966:ios:80cb5c87bcdbc10c8c83cf',
    messagingSenderId: '148134255966',
    projectId: 'inkwave-01',
    storageBucket: 'inkwave-01.firebasestorage.app',
    androidClientId: '148134255966-tp1pre8en9le6eqhmbgsb95ragmi6krv.apps.googleusercontent.com',
    iosClientId: '148134255966-tjmiktovlvuq300ehu8p0mrf7q1ok1l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.inkwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1iKcqKZWxJcexSdTucSAbPMDEb7pFYw',
    appId: '1:148134255966:web:bbc45efced6f007e8c83cf',
    messagingSenderId: '148134255966',
    projectId: 'inkwave-01',
    authDomain: 'inkwave-01.firebaseapp.com',
    storageBucket: 'inkwave-01.firebasestorage.app',
  );

}